# Generated by Django 4.1.6 on 2023-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="Photo",
            field=models.ImageField(upload_to="Emp_Images/"),
        ),
    ]
