# Generated by Django 4.1.6 on 2023-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0002_alter_employee_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="Photo",
            field=models.ImageField(blank=True, null=True, upload_to="Emp_Images/"),
        ),
    ]
