# Generated by Django 4.1.6 on 2023-06-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0003_alter_employee_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="Resume",
        ),
    ]
