# Generated by Django 4.1.6 on 2023-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageuploader",
            name="image",
            field=models.ImageField(unique=True, upload_to="images"),
        ),
    ]
