# Generated by Django 4.1.6 on 2023-07-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_alter_resume_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='State',
        ),
    ]
